### ISSUE TITLE
Hosting secondary files, where to place?

### ISSUE THREAD

**Issue by mughal4** [mughal4/xlr.pw#26]
write mods guidelines

**Comment by mughal4** [comment]
completed. Where can I store it to place in chen2.org/mods.txt?

**Comment by setr** [comment]
It looks like css, js, etc are all stored in /assets/...
so css url is: https://chen2.org/assets/css/base.css

/assets/ is probably where **all** static files belong, including something like mods.txt, though this will give you the url https://chen2.org/assets/mods.txt
If you try to do https://chen2.org/mods.txt it'll probably try to read the url as a board and fail the lookup. 

On the server, /assets/ is the folder ~/meguca/www/

**Comment by mughal4** [comment]
Could we create our own folder for it? 
e.g.
chen2.org/txt/mods.txt

**Comment by setr** [comment]
It's pretty stupid but I just made /txt/ an alias to /assets/

So you can now access mods.txt at https://chen2.org/txt/mods.txt
However, the following urls are all valid:
https://chen2.org/assets/mods.txt
https://chen2.org/assets/file.png
https://chen2.org/txt/file.png

etc.

and just passthrough to  the same directory on the server: ~/meguca/www/

**Comment by setr** [comment]
Its fixed now.

https://chen2.org/txt/ -> ~/meguca/assets/txt
https://chen2.org/txt/mods.txt -> ~/meguca/assets/txt/mods.txt
etc
